import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

import { backendProvider, runAddJob, runAddRoute } from '../dist/index.js';

async function createTempWorkspace(prefix = 'webstir-backend-add-') {
  return await fs.mkdtemp(path.join(os.tmpdir(), prefix));
}

async function ensureDir(dir) {
  await fs.mkdir(dir, { recursive: true });
}

async function copyAssetByTarget(workspace, targetPath) {
  const assets = await backendProvider.getScaffoldAssets();
  const asset = assets.find((entry) => entry.targetPath === targetPath);
  assert.ok(asset, `expected scaffold asset ${targetPath}`);
  const destination = path.join(workspace, targetPath);
  await ensureDir(path.dirname(destination));
  await fs.copyFile(asset.sourcePath, destination);
}

async function readJson(filePath) {
  return JSON.parse(await fs.readFile(filePath, 'utf8'));
}

test('runAddRoute writes manifest metadata and patches fastify scaffolding', async () => {
  const workspace = await createTempWorkspace();

  await copyAssetByTarget(workspace, path.join('src', 'backend', 'server', 'fastify.ts'));
  await fs.writeFile(
    path.join(workspace, 'package.json'),
    JSON.stringify(
      {
        name: '@demo/api',
        version: '1.0.0',
        type: 'module',
        webstir: { mode: 'api', moduleManifest: {} },
      },
      null,
      2,
    ),
    'utf8',
  );

  const result = await runAddRoute({
    workspaceRoot: workspace,
    name: 'accounts',
    method: 'POST',
    path: '/api/accounts',
    fastify: true,
    summary: 'List accounts',
    description: 'Returns the current account list',
    tags: ['accounts', 'api', 'accounts'],
    paramsSchema: 'zod:AccountParams@src/shared/contracts/accounts.ts',
    responseSchema: 'AccountList@src/shared/contracts/accounts.ts',
    responseStatus: '201',
  });

  assert.equal(result.subject, 'route');
  assert.ok(result.changes.includes('package.json'));
  assert.ok(result.changes.includes('src/backend/server/routes/accounts.ts'));
  assert.ok(result.changes.includes('src/backend/server/fastify.ts'));

  const pkg = await readJson(path.join(workspace, 'package.json'));
  assert.deepEqual(pkg.webstir.moduleManifest.routes, [
    {
      name: 'accounts',
      method: 'POST',
      path: '/api/accounts',
      summary: 'List accounts',
      description: 'Returns the current account list',
      tags: ['accounts', 'api'],
      input: {
        params: {
          kind: 'zod',
          name: 'AccountParams',
          source: 'src/shared/contracts/accounts.ts',
        },
      },
      output: {
        body: {
          kind: 'zod',
          name: 'AccountList',
          source: 'src/shared/contracts/accounts.ts',
        },
        status: 201,
      },
    },
  ]);

  const routeFile = await fs.readFile(
    path.join(workspace, 'src', 'backend', 'server', 'routes', 'accounts.ts'),
    'utf8',
  );
  const fastifyFile = await fs.readFile(
    path.join(workspace, 'src', 'backend', 'server', 'fastify.ts'),
    'utf8',
  );
  assert.match(routeFile, /Generated by webstir add-route --fastify/);
  assert.match(
    fastifyFile,
    /import \{ register as registerAccounts \} from '\.\/routes\/accounts';/,
  );
  assert.match(fastifyFile, /registerAccounts\(app\);/);
});

test('runAddJob writes a job scaffold and preserves description in a valid manifest', async () => {
  const workspace = await createTempWorkspace('webstir-backend-add-job-');

  await copyAssetByTarget(workspace, path.join('src', 'backend', 'index.ts'));
  await fs.writeFile(
    path.join(workspace, 'package.json'),
    JSON.stringify(
      {
        name: '@demo/api',
        version: '1.0.0',
        type: 'module',
        webstir: { mode: 'api', moduleManifest: {} },
      },
      null,
      2,
    ),
    'utf8',
  );

  const result = await runAddJob({
    workspaceRoot: workspace,
    name: 'nightly',
    schedule: '0 0 * * *',
    description: 'Nightly maintenance run',
    priority: '5',
  });

  assert.equal(result.subject, 'job');
  assert.ok(result.changes.includes('package.json'));
  assert.ok(result.changes.includes('src/backend/jobs/nightly/index.ts'));

  const pkg = await readJson(path.join(workspace, 'package.json'));
  assert.deepEqual(pkg.webstir.moduleManifest.jobs, [
    {
      name: 'nightly',
      schedule: '0 0 * * *',
      description: 'Nightly maintenance run',
      priority: 5,
    },
  ]);

  const buildResult = await backendProvider.build({
    workspaceRoot: workspace,
    env: {
      WEBSTIR_MODULE_MODE: 'build',
      WEBSTIR_BACKEND_TYPECHECK: 'skip',
      PATH: process.env.PATH ?? '',
    },
    incremental: false,
  });

  assert.deepEqual(buildResult.manifest.module?.jobs, [
    {
      name: 'nightly',
      schedule: '0 0 * * *',
      description: 'Nightly maintenance run',
      priority: 5,
    },
  ]);
});
