import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorials: [
    {
      type: 'category',
      label: 'Tutorials',
      link: {type: 'doc', id: 'tutorials/README'},
      items: [
        'tutorials/getting-started',
        'tutorials/first-app',
        'tutorials/backend-loop',
      ],
    },
  ],
  howTo: [{type: 'autogenerated', dirName: 'how-to'}],
  reference: [{type: 'autogenerated', dirName: 'reference'}],
  explanations: [{type: 'autogenerated', dirName: 'explanations'}],
};

export default sidebars;
